parameters:
  projectFileName: PowerShellV1ExecutionTests
  testType: 'Execution'
steps:
- task: PowerShell@2
  displayName: Install Required Modules
  inputs:
    targetType: 'inline'
    script: |
        if (!(Get-Module -Name Microsoft.Graph -ListAvailable)) {
            Install-Module Microsoft.Graph -Repository PSGallery -Scope AllUsers -Force -AllowClobber
            Import-Module Microsoft.Graph -Global -Force 
        }
- template: ../common-templates/checkout.yml
- template: ../compile-run-tests-template.yml
  parameters:
    projectFileName: ${{ parameters.projectFileName }}
    runName: ${{ parameters.projectFileName }}
    testType: ${{ parameters.testType }}